### ISSUE TITLE
Error on mix compile

### ISSUE THREAD

**Issue by zeropoid** [kblake/neural_network_elixir#1]
Can't issue mix compile, cuz getting this error: 

http://prntscr.com/e76x90

**Comment by kblake** [comment]
@zeropoid I just cloned fresh, ran `mix deps.get` and `mix deps.compile` and it successfully compiles. Do you have other details to share: commands you ran, Elixir version, etc?

**Comment by kblake** [comment]
@zeropoid Have you tried lately. There were a lot of warnings due to a new version of Elixir. I've cleaned that up. Let me know.

**Comment by PhillippOhlandt** [comment]
I think he just didn't install the dependencies.

**Comment by kblake** [comment]
@PhillippOhlandt Yes, very well could be. @zeropoid Would you mind trying again?

**Comment by zeropoid** [comment]
Solved. Thank you. In new version everything is fine now. Also: I installed all dependencies :D

**Comment by kblake** [comment]
@zeropoid Yay! Thanks for checking.
