### ISSUE TITLE
Unlike the example, my OR value never drops below 0.06, even at 50k epochs

### ISSUE THREAD

**Issue by DeadZen** [kblake/neural_network_elixir#2]
The example seems it hits a much lower error rate much sooner, 

OR gate learning *********************************************
Epoch: 0   Error: 0.1017313643758654962
Epoch: 1000   Error: 0.0706510268483878101
Epoch: 2000   Error: 0.0694078737649472255
Epoch: 3000   Error: 0.0691257812040881742
Epoch: 4000   Error: 0.0690138235939637135
Epoch: 5000   Error: 0.0689560625073349087
Epoch: 6000   Error: 0.0689214399726986449
Epoch: 7000   Error: 0.0688985888357449283
Epoch: 8000   Error: 0.0688824663549667399
Epoch: 9000   Error: 0.0688705226610778765
Epoch: 10000   Error: 0.0688613400497658651
Epoch: 11000   Error: 0.0688540714582587809
Epoch: 12000   Error: 0.0688481813786790686
Epoch: 13000   Error: 0.0688433155227795718
Epoch: 14000   Error: 0.0688392305714215086
Epoch: 15000   Error: 0.0688357541121761146
Epoch: 16000   Error: 0.068832760693236919
Epoch: 17000   Error: 0.0688301569297410099
Epoch: 18000   Error: 0.0688278719191780519
Epoch: 19000   Error: 0.0688258508884135589
Epoch: 20000   Error: 0.0688240508724281413
Epoch: 21000   Error: 0.0688224377071812304
Epoch: 22000   Error: 0.0688209838940851831
Epoch: 23000   Error: 0.0688196670556822931
Epoch: 24000   Error: 0.0688184688004635642
Epoch: 25000   Error: 0.0688173738760124165
Epoch: 26000   Error: 0.0688163695286981153
Epoch: 27000   Error: 0.0688154450135683715
Epoch: 28000   Error: 0.0688145912149670941
Epoch: 29000   Error: 0.0688138003498121181
Epoch: 30000   Error: 0.068813065733296791
Epoch: 31000   Error: 0.0688123815922419002
Epoch: 32000   Error: 0.0688117429151831328
Epoch: 33000   Error: 0.0688111453310412957
Epoch: 34000   Error: 0.0688105850102238015
Epoch: 35000   Error: 0.0688100585834713202
Epoch: 36000   Error: 0.0688095630748492698
Epoch: 37000   Error: 0.0688090958460928354
Epoch: 38000   Error: 0.0688086545501263441
Epoch: 39000   Error: 0.0688082370920427566
Epoch: 40000   Error: 0.0688078415961832918
Epoch: 41000   Error: 0.0688074663782366758
Epoch: 42000   Error: 0.0688071099214858234
Epoch: 43000   Error: 0.0688067708565030245
Epoch: 44000   Error: 0.0688064479437225374
Epoch: 45000   Error: 0.0688061400584276117
Epoch: 46000   Error: 0.0688058461777701774
Epoch: 47000   Error: 0.0688055653695099356
Epoch: 48000   Error: 0.068805296782213185
Epoch: 49000   Error: 0.0688050396366947509
Epoch: 49999   Error: 0.0688047934598075839
Epoch: 50000   Error: 0.0688047932185247568
**************************************************************

**Comment by knewter** [comment]
So this is actually because the mix task that sets up the network always uses a single input. you need to accept two inputs. here's how I verified that `or` works: https://github.com/knewter/neural_network_elixir/blob/feature/or/lib/mix/tasks/or.ex

Also I think I've identified that hidden layers aren't working correctly. I can't train it on `xor` to a successful state. I think I know why but need to read a little more on how the hidden layer training should work before I can be sure.

**Comment by kblake** [comment]
@knewter Thanks for catching my oversight! I'll be fixing that. :)

**Comment by kblake** [comment]
@DeadZen @knewter `learn.ex` has been updated with 2 inputs which should have an impact on the outcome.
